sonar.projectKey=revisium_agent-orchestrator-admin
sonar.organization=revisium
sonar.exclusions=src/__generated__/**,build/**,dist/**,coverage/**,.sonar/**,.scannerwork/**,node_modules/**,src/vite-env.d.ts
