sonar.projectKey=revisium_agent-orchestrator-admin
sonar.organization=revisium
sonar.coverage.exclusions=src/**
sonar.exclusions=src/__generated__/**,build/**,dist/**,coverage/**,.sonar/**,.scannerwork/**,node_modules/**,src/vite-env.d.ts
sonar.cpd.exclusions=src/__generated__/**,src/shared/fixtures/**
